/**
 * role_context.ts — Role Context Protocol
 *
 * Before activating a role, R11 generates a context file that contains
 * everything the role needs to function in its isolated Agent context.
 *
 * This solves the platform limitation where Agent tool subagents
 * do not inherit the main conversation's file context.
 *
 * Context levels by role category:
 *   DOC_ROLES (R01-R05, R10): document-based, ~2-5K tokens
 *   CODE_ROLES (R06-R09): need actual source code, ~10-30K tokens
 *   ORCH_ROLES (R11): governance files only, ~500 tokens
 */

import { readFileSync, readdirSync, existsSync, statSync } from "node:fs";
import { join, relative, resolve } from "node:path";

// ── Role Categories ──────────────────────────────────────

type RoleCategory = "doc" | "code" | "orch";

const ROLE_CATEGORIES: Record<string, RoleCategory> = {
  R01: "doc", R02: "doc", R03: "doc", R04: "doc", R05: "doc",
  R06: "code", R07: "code", R08: "code", R09: "code",
  R10: "doc", R11: "orch",
};

/** Roles that need source code context injected. */
const CODE_ROLES = new Set(["R06", "R07", "R08", "R09"]);

/** Roles that need architecture/design document context. */
const DOC_ROLES = new Set(["R01", "R02", "R03", "R04", "R05", "R10"]);

/** Maximum total content size for code injection (bytes) to stay within token budget. */
const MAX_CODE_CONTENT_BYTES = 50_000;
/** Maximum individual file size (bytes). Files larger than this are listed but not included. */
const MAX_SINGLE_FILE_BYTES = 5_000;

// ── Context Generation ───────────────────────────────────

export interface RoleContextResult {
  role_id: string;
  category: RoleCategory;
  context_file: string;
  sections: string[];
  estimated_tokens: number;
}

/**
 * Generate a complete context file for a role and write it to .ai/role-context/.
 * Returns metadata about what was generated.
 */
export function generateRoleContext(
  projectRoot: string,
  roleId: string,
): RoleContextResult {
  const category = ROLE_CATEGORIES[roleId] ?? "doc";
  const sections: string[] = [];
  const lines: string[] = [];

  lines.push(`# Role Context: ${roleId}`);
  lines.push("");
  lines.push(`> Auto-generated by role_context.ts at ${new Date().toISOString()}`);
  lines.push(`> Category: ${category}`);
  lines.push("");

  // ── 1. Role Contract ──
  const contract = loadRoleContract(projectRoot, roleId);
  if (contract) {
    lines.push("## Role Contract");
    lines.push("");
    lines.push(contract);
    sections.push("contract");
  }

  // ── 2. Project Structure (all roles) ──
  const structure = generateProjectStructure(projectRoot);
  lines.push("## Project Structure");
  lines.push("");
  lines.push("```");
  lines.push(structure);
  lines.push("```");
  sections.push("structure");

  // ── 3. Governance State ──
  const govState = generateGovernanceSummary(projectRoot);
  if (govState) {
    lines.push("## Governance State");
    lines.push("");
    lines.push(govState);
    sections.push("governance");
  }

  // ── 4. Role-specific content ──
  if (CODE_ROLES.has(roleId)) {
    const codeCtx = generateCodeContext(projectRoot, roleId);
    lines.push(codeCtx);
    sections.push("code_context");
  }

  if (DOC_ROLES.has(roleId)) {
    const docCtx = generateDocContext(projectRoot, roleId);
    lines.push(docCtx);
    sections.push("doc_context");
  }

  // ── 5. Thinking Framework ──
  const thinkingFramework = loadThinkingFramework(projectRoot, roleId);
  if (thinkingFramework) {
    lines.push("## Thinking Framework");
    lines.push("");
    lines.push(thinkingFramework);
    sections.push("thinking");
  }

  const content = lines.join("\n");
  const estimatedTokens = Math.ceil(content.length / 4);

  // Write context file
  const contextDir = join(projectRoot, ".ai", "role-context");
  if (!existsSync(contextDir)) {
    const { mkdirSync } = require("node:fs");
    mkdirSync(contextDir, { recursive: true });
  }
  const contextFile = join(contextDir, `${roleId}.md`);
  const { writeFileSync } = require("node:fs");
  writeFileSync(contextFile, content, "utf-8");

  return {
    role_id: roleId,
    category,
    context_file: contextFile,
    sections,
    estimated_tokens: estimatedTokens,
  };
}

// ── Private: Role Contract ──────────────────────────────

function loadRoleContract(root: string, roleId: string): string | null {
  const contractPath = join(root, ".ai", "registry", `${roleId}.yaml`);
  if (!existsSync(contractPath)) return null;
  try {
    return readFileSync(contractPath, "utf-8");
  } catch {
    return null;
  }
}

// ── Private: Project Structure ──────────────────────────

function generateProjectStructure(root: string): string {
  const lines: string[] = [];
  const keyDirs = ["src", "tests", "scripts", "docs", "skills"];

  for (const dir of keyDirs) {
    const dirPath = join(root, dir);
    if (!existsSync(dirPath)) continue;
    lines.push(`${dir}/`);
    try {
      const entries = readdirSync(dirPath, { recursive: true, withFileTypes: true });
      const files = entries
        .filter(e => e.isFile())
        .map(e => "  " + relative(root, join(e.parentPath ?? dirPath, e.name)).replace(/\\/g, "/"))
        .slice(0, 50);
      lines.push(...files);
      if (entries.length > 50) lines.push(`  ... and ${entries.length - 50} more files`);
    } catch {
      lines.push("  (unable to list)");
    }
  }

  // Package.json if exists
  const pkgPath = join(root, "package.json");
  if (existsSync(pkgPath)) {
    lines.push("package.json");
  }

  return lines.join("\n");
}

// ── Private: Governance Summary ─────────────────────────

function generateGovernanceSummary(root: string): string | null {
  const statePath = join(root, ".ai", "state.yaml");
  if (!existsSync(statePath)) return null;
  try {
    const content = readFileSync(statePath, "utf-8");
    const lines = content.split("\n").slice(0, 15).join("\n");
    return `\`\`\`yaml\n${lines}\n\`\`\``;
  } catch {
    return null;
  }
}

// ── Private: Code Context (R06-R09) ─────────────────────

function generateCodeContext(root: string, roleId: string): string {
  const lines: string[] = [];
  lines.push("## Source Code Context");
  lines.push("");

  let totalBytes = 0;
  const includedFiles: string[] = [];
  const skippedFiles: string[] = [];

  // Collect source files
  const srcDir = join(root, "src");
  const testDir = join(root, "tests");

  const sourceFiles = collectFiles(srcDir, [".ts"]);
  const testFiles = collectFiles(testDir, [".ts", ".test.ts"]);

  // Prioritize: core module files first
  const priorityPrefixes = ["src/core/", "src/types/"];
  const prioritized = sourceFiles.filter(f =>
    priorityPrefixes.some(p => f.startsWith(p))
  );
  const others = sourceFiles.filter(f =>
    !priorityPrefixes.some(p => f.startsWith(p))
  );

  const orderedFiles = [...prioritized, ...others, ...testFiles];

  for (const file of orderedFiles) {
    const fullPath = join(root, file);
    try {
      const stat = statSync(fullPath);
      if (stat.size > MAX_SINGLE_FILE_BYTES) {
        skippedFiles.push(file);
        continue;
      }
      if (totalBytes + stat.size > MAX_CODE_CONTENT_BYTES) {
        skippedFiles.push(file);
        continue;
      }
      const content = readFileSync(fullPath, "utf-8");
      lines.push(`### ${file}`);
      lines.push("");
      lines.push("```typescript");
      lines.push(content);
      lines.push("```");
      lines.push("");
      includedFiles.push(file);
      totalBytes += stat.size;
    } catch {
      // skip unreadable
    }
  }

  // Summary
  lines.push(`> Included ${includedFiles.length} files (~${Math.ceil(totalBytes / 1024)}KB). Skipped ${skippedFiles.length} files.`);

  return lines.join("\n");
}

// ── Private: Doc Context (R01-R05, R10) ─────────────────

function generateDocContext(root: string, roleId: string): string {
  const lines: string[] = [];
  lines.push("## Document Context");
  lines.push("");

  // Architecture docs for R04/R05
  if (roleId === "R04" || roleId === "R05") {
    appendDocFile(root, lines, ".ai/ARCHITECTURE.md", "Architecture Design");
    appendDocFile(root, lines, ".ai/CODEMAP.md", "Code Map");
    appendDocFile(root, lines, ".ai/CONTRACTS.md", "Interface Contracts");
  }

  // Coding standards for R06 (also reads via code context)
  if (roleId === "R01" || roleId === "R06") {
    appendDocFile(root, lines, ".ai/CODING_STANDARDS.md", "Coding Standards");
    appendDocFile(root, lines, ".ai/CONVENTIONS.md", "Conventions");
  }

  // Quality gates for R07
  if (roleId === "R07") {
    appendDocFile(root, lines, ".ai/QUALITY_GATES.md", "Quality Gates");
  }

  // Non-goals and known issues for product/architecture
  if (roleId === "R01" || roleId === "R04") {
    appendDocFile(root, lines, ".ai/NON_GOALS.md", "Non-Goals");
    appendDocFile(root, lines, ".ai/KNOWN_ISSUES.md", "Known Issues");
  }

  if (lines.length <= 2) {
    lines.push("(No specific documents loaded for this role)");
    lines.push("");
  }

  return lines.join("\n");
}

// ── Private: Thinking Framework ─────────────────────────

function loadThinkingFramework(root: string, roleId: string): string | null {
  const frameworkPath = join(root, ".ai", "thinking-framework.md");
  if (!existsSync(frameworkPath)) return null;
  try {
    const content = readFileSync(frameworkPath, "utf-8");
    // Extract section for this role
    const rolePattern = new RegExp(`## ${roleId}[^#]*`, "i");
    const sectionMatch = content.match(rolePattern);
    if (sectionMatch) return sectionMatch[0];
    // Fallback: return the generic section
    const genericMatch = content.match(/## 通用思维框架[^#]*/);
    return genericMatch ? genericMatch[0] : null;
  } catch {
    return null;
  }
}

// ── Helpers ─────────────────────────────────────────────

function collectFiles(dir: string, exts: string[]): string[] {
  if (!existsSync(dir)) return [];
  const results: string[] = [];
  try {
    const entries = readdirSync(dir, { recursive: true, withFileTypes: true });
    for (const e of entries) {
      if (!e.isFile()) continue;
      const fullPath = join(e.parentPath ?? dir, e.name);
      const relPath = relative(resolve("."), fullPath).replace(/\\/g, "/");
      if (exts.some(ext => e.name.endsWith(ext))) {
        results.push(relPath);
      }
    }
  } catch { /* skip */ }
  return results;
}

function appendDocFile(root: string, lines: string[], relPath: string, title: string): void {
  const fullPath = join(root, relPath);
  if (!existsSync(fullPath)) return;
  try {
    const content = readFileSync(fullPath, "utf-8");
    lines.push(`### ${title}`);
    lines.push("");
    lines.push(content.slice(0, 3000)); // Limit per doc
    if (content.length > 3000) lines.push("...(truncated)");
    lines.push("");
  } catch { /* skip */ }
}
